#!/bin/bash
if [ "$1" == "" ]; then
	echo "Usage: ./deploy_ifcfg <name-of-src-cfg-file> <name-of-des-cfg-file>"
	exit
fi

echo "Copied $1 to /etc/sysconfig/network-scripts/$2"
sudo cp $1 /etc/sysconfig/network-scripts/$2
echo "Restarting network service ..."
sudo service network restart
