#!/bin/bash
if [ "$1" == "" ]; then
	echo "Usage: /.launch_instance <image-name> <key-name (without \".private\")>"
	exit
fi
echo "Launching an instance ..."
euca-run-instances $1 -k $2

#echo "Instance status: "
#euca-describe-instances <instance_id>
